# springboot related config file

logging:
  level:
    com: INFO

server:
  port: 8090

credentials:
  # Java SDK domains supporting unified credentials
  # - Numbers
  # - SMS: US/EU are the only supported regions with unified credentials
  # - Conversation
  project-id:
  key-id:
  key-secret:

  # Application related credentials, used by:
  # - Verification
  # - Voice
  application-api-key:
  application-api-secret:

# Secret value set for Numbers webhooks calls validation
numbers:
  webhooks:
    secret:

# Secret value set for Conversation webhooks calls validation
conversation:
  # Sets the region for Conversation
  # See https://github.com/sinch/sinch-sdk-java/blob/main/client/src/main/com/sinch/sdk/models/ConversationRegion.java for list of supported values
  region:
  webhooks:
    secret:

sms:
  # Sets the region for SMS
  # valid values are "us" and "eu"
  # See https://github.com/sinch/sinch-sdk-java/blob/main/client/src/main/com/sinch/sdk/models/SMSRegion.java for full list of supported values but with servicePlanID
  region:
  webhooks:
    secret:
